// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvS4OPLDJW_X-Y58Unph2S_8uFMt2gCOI',
    appId: '1:825737501566:web:423099903801ffd472312f',
    messagingSenderId: '825737501566',
    projectId: 'flutter-recipes-firebase',
    authDomain: 'flutter-recipes-firebase.firebaseapp.com',
    storageBucket: 'flutter-recipes-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKuqdJdULlp7OujHJ8VHUCccHFig5kgSo',
    appId: '1:825737501566:android:449669fa97779fab72312f',
    messagingSenderId: '825737501566',
    projectId: 'flutter-recipes-firebase',
    storageBucket: 'flutter-recipes-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDitD4X-LSM7DGVW_IJ-pW2pXTZxK6CwF0',
    appId: '1:825737501566:ios:1bb764fee679531c72312f',
    messagingSenderId: '825737501566',
    projectId: 'flutter-recipes-firebase',
    storageBucket: 'flutter-recipes-firebase.appspot.com',
    androidClientId: '825737501566-pi7d6075eq1oct9i0nj1reokv23lm3so.apps.googleusercontent.com',
    iosClientId: '825737501566-4qg41mr05d2e3sgt3ib98u4s7nb7r4b1.apps.googleusercontent.com',
    iosBundleId: 'com.julian.otto.flutterRecipes',
  );
}
